# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vinicius Bisognin Immich
tagline:          'Website'
description:      'Developer & Teacher'
url:              http://vinibiso.github.io/
baseurl:          /

author:
  name:           'Vinicius Bisognin Immich'
  url:            http://vinibiso.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vinibiso/vinibiso/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown